name: Run Golang
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Go 1.15
      uses: cedrickring/golang-action/go1.15@1.6.0
    - name: Run demo.go
      run: |
        go run example/demo.go